package com.example.mimshak_final_afekoin

import kotlinx.serialization.Serializable
import java.util.Date

@Serializable
data class Transaction(
    // We don't need to send the id when creating, so it has a default value
    val id: Int = 0, 
    // We mark fields that are auto-generated by the database as nullable
    // so we don't have to provide them when inserting a new transaction.
    val created_at: String? = null, 
    val user_id: String, 
    val description: String,
    val amount: Double
)
